apiVersion: v1
kind: Service
metadata:
  name: node-microservice-svc
spec:
  type: LoadBalancer
  selector:
    app: node-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
